apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
spec:
  selector:
      matchLabels:
        app: webapi
  replicas: 2
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - name: webapi
          image: amirelgammal/webapi:v1
          ports:
            - containerPort: 80
          env:
           - name: NGINX
             value: http://localhost
  strategy:
    type: RollingUpdate              
---            
kind: Service
apiVersion: v1
metadata:
  name: webapi
spec:
  selector:
    app: webapi
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileserver
spec:
  selector:
      matchLabels:
        app: fileserver
  replicas: 1
  template:
    metadata:
      labels:
        app: fileserver
    spec:
      containers:
        - name: fileserver
          image: amirelgammal/nginx:v1
          ports:
            - containerPort: 80
  strategy:
    type: RollingUpdate
---
kind: Service
apiVersion: v1
metadata:
  name: fileserver
spec:
  selector:
    app: fileserver
  ports:
  - protocol: TCP
    port: 80
  type: ClusterIP