---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testapi
  labels:
    app: testapi
    visualize: "true"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testapi
        visualize: "true"
    spec:
      containers:
      - name: testapi
        image: testapi:v1
        ports:
        - name: web
          containerPort: 5555
          hostPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: testapi
spec:
  selector:
    app: testapi
  ports:
  - name: http
    port: 5555
    targetPort: 5555
    nodePort: 30555
  type: NodePort