apiVersion: v1
kind: Service
metadata:
  name: testapi
  labels:
    app: testapi
spec:
  type: LoadBalancer
  selector:
    app: testapi
  ports:
  - port: 5000
    name: http
    targetPort: 5000
    nodePort: 5000
